import type { Metadata } from 'next'

import '../scss/index.scss'
import Lenis from '@/components/Lenis'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<Lenis>
				<body>
					<main>{children}</main>
				</body>
			</Lenis>
		</html>
	)
}
